# pensando en media montaña con frío (Iztaccihuatl)
ropa:
  capas:
    1:
      - Pijama térmica
      - Calcetines
    2:
      - suéter de polar
      - pants
      - otros calcetines
      - calzado impermeable
    3:
      - Chamarra impermeable calientita
      - oberol o pantalón grueso (opcional, en caso de extremo frío (alta montaña))
  extras:
    - guantes (considérense unos que se adhieran a la piel)
    - gorro
    - impermeable ligero
    - lentes
  notas:
    - La ropa debería ser en su mayoría sintética, o tener la cualidad de secarse rápido (el algodón no hace eso)

# sugerencias de cosas que comer
# vale la pena recordar que es difícil calentar cosas en la montaña
# así que hay que llevar cosas ya preparadas y de fácil empaquetado
# uno carga su propia comida así que hay que ver lo del espacio y el peso
# la comida es personal pero arriba siempre se comparte (:
comida:
  - quesadillas
  - semillas
  - fruta seca
  - pasas
  - chocolate
  - barritas
  - alegrias
  - maruchan
  - te o café
  - derivados...

demás:
  - sleeping bag
  - bajoalfombra (se pone bajo el sleeping para aislar el frío, un tapete para yoga es suficiente)
  - lámpara y pilas
  - mochila (no se debería llevar nada en las manos, por precaución)
  - cuchillo (nunca sabes cuándo te tienes que comer a tus compañeros)